# Generated by Django 2.2.5 on 2019-09-29 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='list_upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('1', 'List'), ('2', 'Segment'), ('3', 'Testmail'), ('4', 'Transactional Mail')], max_length=1)),
                ('name', models.CharField(max_length=50)),
                ('uploadBtn', models.FileField(upload_to='')),
                ('datacount', models.IntegerField(default=0)),
                ('addeddate', models.DateTimeField()),
                ('uid', models.CharField(max_length=20)),
            ],
        ),
    ]
